#!/usr/bin/env bash
# Learn-apply — carry filled improvement proposals into a PR. Never commits to main.
#
# Suggest-only by default (DRY_RUN=1, same contract as the maintenance routines):
# it prints exactly what it would do. DRY_RUN=0 creates a branch, commits ONLY the
# proposal files, pushes, and opens the PR. The change to CLAUDE.md/rules/skills is
# made by a human inside that PR — never by this script (prime directive 5).
#
# Usage: learn-apply.sh            (DRY_RUN=1 default; DRY_RUN=0 to really open the PR)
set -euo pipefail

ADF="${ADF:-ai-development-framework}"
PROP_DIR="$ADF/docs/traces/proposals"
DRY_RUN="${DRY_RUN:-1}"
case "$DRY_RUN" in 0|1) ;; *) echo "✗ DRY_RUN must be 0 or 1" >&2; exit 2 ;; esac

command -v git >/dev/null 2>&1 || { echo "✗ git required" >&2; exit 2; }
git rev-parse --git-dir >/dev/null 2>&1 || { echo "✗ not a git repository" >&2; exit 2; }

echo "▶ learn-apply (dry-run=$DRY_RUN)"

# A proposal still carrying the `…` placeholders is an unfilled stub, not a proposal.
filled=()
for f in "$PROP_DIR"/*.md; do
  [ -f "$f" ] || continue
  [ "$(basename "$f")" = TEMPLATE.md ] && continue
  if grep -q '…' "$f"; then echo "  ~ skipped (unfilled stub): $f"; continue; fi
  filled+=("$f")
done
[ ${#filled[@]} -gt 0 ] || { echo "✗ no filled proposals — run 'make learn', fill the stubs, then retry"; exit 1; }

branch="${BRANCH:-learn/proposals-$(date -u '+%Y%m%d-%H%M%S')}"
title="learn: ${#filled[@]} improvement proposal(s) from recorded failures"
printf '  proposals: %s\n' "${filled[@]}"
echo "  branch: $branch"
echo "  PR title: $title"

if [ "$DRY_RUN" = 1 ]; then
  echo "  Dry run — nothing committed or pushed. Re-run with DRY_RUN=0 to open the PR."
  exit 0
fi

command -v gh >/dev/null 2>&1 || { echo "✗ gh absent — install GitHub CLI, or push '$branch' and open the PR manually" >&2; exit 2; }
git switch -c "$branch"
# Path-limited add+commit: unrelated staged work never rides along in this PR.
git add -- "${filled[@]}"
git commit -m "$title" -- "${filled[@]}"
git push -u origin "$branch"
gh pr create --title "$title" --body "Proposals generated by \`make learn\` from recorded failures.

Human decision required: this PR carries evidence and a proposed change. Applying it to
\`CLAUDE.md\`, \`rules/\`, \`skills/\` or \`hooks/\` happens in review, not automatically.

Gates: \`make quality\`, \`make skill-audit\`, \`make mcp-audit\`, \`make graph-check\`."
echo "✓ PR opened from $branch"
