#!/usr/bin/env bash
# Local, structured agent-flow observability. No network and no provider SDK.
set -euo pipefail

ADF="${ADF_DIR:-ai-development-framework}"
DOCS="$ADF/docs/observability"
EVENTS="$DOCS/events.jsonl"
TRAJECTORIES="$DOCS/trajectories"

task="${TASK:-task}"
archetype="${ARCHETYPE:-unknown}"
phase="${PHASE:-handoff}"
tokens_in="${TOKENS_IN:-na}"
tokens_out="${TOKENS_OUT:-na}"
budget_remaining="${BUDGET_REMAINING:-na}"
duration_seconds="${DURATION_SECONDS:-na}"
cost_usd="${COST_USD:-na}"
switched="${SWITCHED:-false}"
trigger="${TRIGGER:-none}"
outcome="${OUTCOME:-in_progress}"

usage() {
  echo "usage: observability.sh <record|complete|summary>"
}

safe_word() {
  [[ "$1" =~ ^[A-Za-z0-9_.:/-]+$ ]]
}

safe_task() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]
}

safe_number() {
  [[ "$1" = "na" || "$1" =~ ^[0-9]+([.][0-9]+)?$ ]]
}

json_number() {
  [ "$1" = "na" ] && printf null || printf '%s' "$1"
}

validate() {
  safe_task "$task" || { echo "✗ observability: TASK must be a filename-safe identifier" >&2; exit 2; }
  for value in "$archetype" "$phase" "$trigger" "$outcome"; do
    safe_word "$value" || { echo "✗ observability: values must use [A-Za-z0-9_.:/-]" >&2; exit 2; }
  done
  for value in "$tokens_in" "$tokens_out" "$budget_remaining" "$duration_seconds" "$cost_usd"; do
    safe_number "$value" || { echo "✗ observability: numeric fields must be a number or na" >&2; exit 2; }
  done
  [[ "$switched" = "true" || "$switched" = "false" ]] || { echo "✗ observability: SWITCHED must be true or false" >&2; exit 2; }
}

record() {
  validate
  mkdir -p "$DOCS" "$TRAJECTORIES"
  local timestamp
  timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf '{"timestamp":"%s","task":"%s","archetype":"%s","phase":"%s","switched":%s,"switch_trigger":"%s","tokens_in":%s,"tokens_out":%s,"budget_remaining":%s,"duration_seconds":%s,"cost_usd":%s,"outcome":"%s"}\n' \
    "$timestamp" "$task" "$archetype" "$phase" "$switched" "$trigger" "$(json_number "$tokens_in")" "$(json_number "$tokens_out")" "$(json_number "$budget_remaining")" "$(json_number "$duration_seconds")" "$(json_number "$cost_usd")" "$outcome" >> "$EVENTS"
  echo "✓ observability: $task/$phase ($archetype)"
}

trajectory() {
  local output="$TRAJECTORIES/$task.trajectory.md"
  {
    echo "# Trajectory — $task"
    echo
    echo "Generated by \`hooks/observability.sh complete\`. JSONL is the source of truth."
    echo
    echo '```jsonl'
    awk -v task="\"task\":\"$task\"" 'index($0, task) { print }' "$EVENTS"
    echo '```'
  } > "$output"
  echo "✓ trajectory: $output"
}

# Counters over the event log. Sets the caller's locals (bash dynamic scope).
count_events() {
  total="$(wc -l < "$EVENTS" | tr -d ' ')"
  switches="$(grep -c '"switched":true' "$EVENTS" || true)"
  succeeded="$(grep -c '"outcome":"success"' "$EVENTS" || true)"
  failed="$(grep -c '"outcome":"failure"' "$EVENTS" || true)"
  tokens="$(awk '
    function add(field,    parts, value) { if (split($0, parts, field) > 1) { split(parts[2], value, ","); if (value[1] ~ /^[0-9]+$/) { total += value[1]; seen = 1 } } }
    { add("\"tokens_in\":"); add("\"tokens_out\":") }
    END { print seen ? total : "na" }
  ' "$EVENTS")"
  cost="$(awk -F'"cost_usd":' 'NF > 1 { split($2, value, ","); if (value[1] ~ /^[0-9.]+$/) { total += value[1]; seen = 1 } } END { if (seen) printf "%.6f", total; else print "na" }' "$EVENTS")"
}

# Eval signal — the Evaluation-Driven Development half of the loop. `resolved` is the
# outcome column of docs/evals/results.csv; skipped runs are no signal, never a pass.
count_evals() {
  local csv="$ADF/docs/evals/results.csv"
  [ -f "$csv" ] || return 0
  evals="$(( $(wc -l < "$csv") - 1 ))"
  eval_pass="$(awk -F, 'NR>1 && $4=="yes"' "$csv" | wc -l | tr -d ' ')"
  eval_fail="$(awk -F, 'NR>1 && $4=="no"'  "$csv" | wc -l | tr -d ' ')"
  eval_cases="$(awk -F, 'NR>1 && $3!="" {c[$3]=1} END {print length(c)}' "$csv")"
}

rate() { awk -v n="$1" -v d="$2" 'BEGIN { if (d+0 > 0) printf "%.1f%%", 100*n/d; else print "na" }'; }

summary() {
  local total switches succeeded failed tokens cost evals eval_pass eval_fail eval_cases
  total=0; switches=0; succeeded=0; failed=0; tokens=na; cost=na
  evals=0; eval_pass=0; eval_fail=0; eval_cases=0
  [ -f "$EVENTS" ] && count_events
  count_evals
  echo "observability: events=$total success=$succeeded success_rate=$(rate "$succeeded" "$((succeeded + failed))") failure=$failed switches=$switches switch_rate=$(rate "$switches" "$total") tokens=$tokens cost_usd_estimate=$cost eval_runs=$evals"
  echo "evals: cases=$eval_cases runs=$evals resolved=$eval_pass failed=$eval_fail resolve_rate=$(rate "$eval_pass" "$((eval_pass + eval_fail))") (source: docs/evals/results.csv — 'make eval' refreshes, 'make learn' diagnoses)"
}

case "${1:-}" in
  record) record ;;
  complete) record; trajectory ;;
  summary) summary ;;
  *) usage; exit 2 ;;
esac
