#!/usr/bin/env bash
# Local, structured agent-flow observability. No network and no provider SDK.
set -euo pipefail

ADF="${ADF_DIR:-ai-development-framework}"
DOCS="$ADF/docs/observability"
EVENTS="$DOCS/events.jsonl"
TRAJECTORIES="$DOCS/trajectories"

task="${TASK:-task}"
archetype="${ARCHETYPE:-unknown}"
phase="${PHASE:-handoff}"
tokens_in="${TOKENS_IN:-na}"
tokens_out="${TOKENS_OUT:-na}"
budget_remaining="${BUDGET_REMAINING:-na}"
duration_seconds="${DURATION_SECONDS:-na}"
cost_usd="${COST_USD:-na}"
switched="${SWITCHED:-false}"
trigger="${TRIGGER:-none}"
outcome="${OUTCOME:-in_progress}"

usage() {
  echo "usage: observability.sh <record|complete|summary>"
}

safe_word() {
  [[ "$1" =~ ^[A-Za-z0-9_.:/-]+$ ]]
}

safe_task() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]
}

safe_number() {
  [[ "$1" = "na" || "$1" =~ ^[0-9]+([.][0-9]+)?$ ]]
}

json_number() {
  [ "$1" = "na" ] && printf null || printf '%s' "$1"
}

validate() {
  safe_task "$task" || { echo "✗ observability: TASK must be a filename-safe identifier" >&2; exit 2; }
  for value in "$archetype" "$phase" "$trigger" "$outcome"; do
    safe_word "$value" || { echo "✗ observability: values must use [A-Za-z0-9_.:/-]" >&2; exit 2; }
  done
  for value in "$tokens_in" "$tokens_out" "$budget_remaining" "$duration_seconds" "$cost_usd"; do
    safe_number "$value" || { echo "✗ observability: numeric fields must be a number or na" >&2; exit 2; }
  done
  [[ "$switched" = "true" || "$switched" = "false" ]] || { echo "✗ observability: SWITCHED must be true or false" >&2; exit 2; }
}

record() {
  validate
  mkdir -p "$DOCS" "$TRAJECTORIES"
  local timestamp
  timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf '{"timestamp":"%s","task":"%s","archetype":"%s","phase":"%s","switched":%s,"switch_trigger":"%s","tokens_in":%s,"tokens_out":%s,"budget_remaining":%s,"duration_seconds":%s,"cost_usd":%s,"outcome":"%s"}\n' \
    "$timestamp" "$task" "$archetype" "$phase" "$switched" "$trigger" "$(json_number "$tokens_in")" "$(json_number "$tokens_out")" "$(json_number "$budget_remaining")" "$(json_number "$duration_seconds")" "$(json_number "$cost_usd")" "$outcome" >> "$EVENTS"
  echo "✓ observability: $task/$phase ($archetype)"
}

trajectory() {
  local output="$TRAJECTORIES/$task.trajectory.md"
  {
    echo "# Trajectory — $task"
    echo
    echo "Generated by \`hooks/observability.sh complete\`. JSONL is the source of truth."
    echo
    echo '```jsonl'
    awk -v task="\"task\":\"$task\"" 'index($0, task) { print }' "$EVENTS"
    echo '```'
  } > "$output"
  echo "✓ trajectory: $output"
}

summary() {
  local total switches succeeded failed tokens cost evals success_rate switch_rate
  total=0; switches=0; succeeded=0; failed=0; tokens=na; cost=na; evals=0; success_rate=na; switch_rate=na
  if [ -f "$EVENTS" ]; then
    total="$(wc -l < "$EVENTS" | tr -d ' ')"
    switches="$(grep -c '"switched":true' "$EVENTS" || true)"
    succeeded="$(grep -c '"outcome":"success"' "$EVENTS" || true)"
    failed="$(grep -c '"outcome":"failure"' "$EVENTS" || true)"
    tokens="$(awk '
      function add(field,    parts, value) { if (split($0, parts, field) > 1) { split(parts[2], value, ","); if (value[1] ~ /^[0-9]+$/) { total += value[1]; seen = 1 } } }
      { add("\"tokens_in\":"); add("\"tokens_out\":") }
      END { print seen ? total : "na" }
    ' "$EVENTS")"
    cost="$(awk -F'"cost_usd":' 'NF > 1 { split($2, value, ","); if (value[1] ~ /^[0-9.]+$/) { total += value[1]; seen = 1 } } END { if (seen) printf "%.6f", total; else print "na" }' "$EVENTS")"
  fi
  if [ -f "$ADF/docs/evals/results.csv" ]; then
    evals="$(( $(wc -l < "$ADF/docs/evals/results.csv") - 1 ))"
  fi
  [ "$total" -gt 0 ] && switch_rate="$(awk -v n="$switches" -v d="$total" 'BEGIN { printf "%.1f%%", 100*n/d }')"
  [ $((succeeded + failed)) -gt 0 ] && success_rate="$(awk -v n="$succeeded" -v d="$((succeeded + failed))" 'BEGIN { printf "%.1f%%", 100*n/d }')"
  echo "observability: events=$total success=$succeeded success_rate=$success_rate failure=$failed switches=$switches switch_rate=$switch_rate tokens=$tokens cost_usd_estimate=$cost eval_runs=$evals"
}

case "${1:-}" in
  record) record ;;
  complete) record; trajectory ;;
  summary) summary ;;
  *) usage; exit 2 ;;
esac
